- controllers/cdn_origin_controller.go
So that we still detect updates to the Status subresource.
> Don't use generation changed predicate

- internal/discovery/discovery.go
- internal/discovery/discovery_test.go
- main.go
Before trying to start the controllers, thus preventing panics when attempting to watch Ingress resources on clusters on which a specific version is not available.
> [RN-225] Check if ingresses are available

- .github/workflows/deploy-image.yaml
- charts/cdn-origin-controller/Chart.yaml
- charts/cdn-origin-controller/values.yaml
Changelog:
- use "v" prefix on image tags ([ref](https://github.com/docker/metadata-action#typesemver))
- bump chart version to `v0.0.3` and image version to `v0.0.4`
> Release v0.0.4

- README.md
- controllers/cloudfront.go
- controllers/ingress_dto.go
- controllers/ingress_reconciler.go
- internal/cloudfront/origin.go
- internal/cloudfront/origin_test.go
- internal/cloudfront/repository.go
- internal/cloudfront/repository_test.go
All behaviors generated from the Ingress resource will share the same function. When this is unwanted it's advised to split the Ingress configuration into multiple  resources, each with their own configuration for this.
> [RN-244] Implement annotation to configure CF viewer request function association

- .gitignore
- Makefile
- README.md
- api/v1alpha1/cdnstatus_types.go
- api/v1alpha1/cdnstatus_types_test.go
- charts/cdn-origin-controller/templates/role.yaml
- config/rbac/role.yaml
- config/samples/multiple_ing_same_group.yaml
- controllers/cloudfront.go
- controllers/cloudfront_test.go
- controllers/ingress_reconciler.go
- controllers/ingress_v1_controller.go
- controllers/ingress_v1beta1_controller.go
- controllers/predicate.go
- controllers/predicate_test.go
- internal/cloudfront/distribution.go
- internal/cloudfront/distribution_test.go
- internal/cloudfront/repository.go
- internal/cloudfront/repository_test.go
- main.go
Changelog:
- the controller is now able to deal with Ingresses being deleted or whose group annotation has been removed, implying they're no longer part of the distribution
- when all ingresses from a group are removed the distribution is now deleted
> [RN-291] Support removal of Ingresses and deletion

- README.md
- controllers/cloudfront.go
- controllers/cloudfront_test.go
- controllers/ingress_params.go
- controllers/ingress_reconciler.go
- controllers/ingress_reconciler_test.go
- controllers/ingress_v1_controller.go
- controllers/ingress_v1beta1_controller.go
- controllers/user_origin.go
- controllers/user_origin_test.go
- go.mod
- internal/cloudfront/distribution.go
- internal/cloudfront/distribution_test.go
- internal/cloudfront/origin.go
- internal/cloudfront/origin_test.go
- internal/cloudfront/repository.go
- internal/cloudfront/repository_test.go
Changelog:
- added `cdn-origin-controller.gympass.com/cf.origin-request-policy` annotation for controlling origin request policies in cache behaviors
- added `cdn-origin-controller.gympass.com/cf.user-origins` annotation for controlling user-supplied origin/behavior definitions to support more complex use-cases that require more granular control
- fixed a bug where two different origins with same host and different configuration (e.g., timeout) were accepted. One of these would eventually be chosen over the other when de-duplicating Origins, leading to one of them being held as "true" while others were ignored.
The controller now returns a reconciliation error if two or more origins with the same hostname are specified with different parameters.
> [RN-318] Support user-supplied origins

- charts/cdn-origin-controller/Chart.yaml
- charts/cdn-origin-controller/templates/deployment.yaml
- charts/cdn-origin-controller/templates/role.yaml
- charts/cdn-origin-controller/templates/role_binding.yaml
- charts/cdn-origin-controller/templates/service.yaml
- charts/cdn-origin-controller/values.yaml
Preventing instances of different classes being deployed with same name for resources in Kubernetes.
> [RN-329] Use CDNClass to avoid resource name collision

- charts/cdn-origin-controller/Chart.yaml
- charts/cdn-origin-controller/templates/role.yaml
- config/rbac/role.yaml
- controllers/ingress_v1_controller.go
- controllers/ingress_v1beta1_controller.go
Preventing errors such as:
```
E1214 13:46:22.922388       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch *v1alpha1.CDNStatus: failed to list *v1alpha1.CDNStatus: cdnstatuses.cdn.gympass.com is forbidden: User "system:serviceaccount:platform:cdn-origin-controller" cannot list resource "cdnstatuses" in API group "cdn.gympass.com" at the cluster scope
```
> [RN-329] Add permissions to handle CDNStatus

- api/v1alpha1/cdnstatus_types.go
- charts/cdn-origin-controller/Chart.yaml
- charts/cdn-origin-controller/templates/role.yaml
- config/crd/bases/cdn.gympass.com_cdnstatuses.yaml
- config/rbac/role.yaml
- controllers/ingress_v1_controller.go
- controllers/ingress_v1beta1_controller.go
Preventing errors when managing the finalizer.
Additionally fixed a bug where a CDNStatus with no DNS records was invalid.
> Grant update permission on Ingresses

- docs/iam_policy.json
Including deletion and tagging of CloudFront distributions, logging
(hence the S3 permissions) and Route53 aliases.
> [RN-334] Add permissions for new features

- api/v1alpha1/cdnstatus_types.go
- controllers/ingress_reconciler.go
- internal/route53/alias.go
- internal/route53/repository.go
Since prefixes didn't work very well for alternate domains that were
also the root of their DNS zone. For example, "foo.com" from the
"foo.com" zone would end up with a TXT record "prefix-foo.com", which
is not valid for the "foo.com" zone, but is valid for the "com" zone.
Now we iterate over each value of a TXT record to determine ownership.
It's ok if there are TXT name collisions.
> [RN-3322] Don't use TXT prefix and check all TXT values for record ownership

- api/v1alpha1/cdnstatus_types.go
- controllers/cloudfront_test.go
- controllers/ingress_reconciler.go
- internal/cloudfront/origin.go
- internal/cloudfront/origin_test.go
- internal/strhelper/strings.go
- internal/strhelper/strings_test.go
To prevent them from reaching the AWS API duplicated, which triggers an error.
Also fixed a couple of bugs on the deletion flow:
- one which would prevent the finalizer from being removed due to Ingress update conflict
- one which would attempt to update the CDNStatus after deleting it
> [RN-341] Handle duplicate paths in the same Origin

- internal/route53/alias.go
- internal/route53/alias_test.go
- internal/route53/repository.go
- internal/route53/repository_test.go
- main.go
Increasing package coverage from 0% to 98.4% (missing 0.6% requires white box testing to be covered).
> [RN-302] Add tests to internal/route53 package

- charts/cdn-origin-controller/Chart.yaml
- charts/cdn-origin-controller/values.yaml
- main.go
To avoid leader election conflicts among COC deployments, we are defining a specific leader election ID per CDN class deployment.
> Setup dynamic leader election based on cdn class

- api/v1alpha1/cdnstatus_types.go
- config/crd/bases/cdn.gympass.com_cdnstatuses.yaml
- internal/cloudfront/service.go
Resolves gympass/production-engineering/issues/118
This PR aims to fix DNS sync status update
Changelog:
* Makes DNS status visible
* Instantiates DNSStatus when status is null
* Sets as successfully synced when process ends without error
> [PE118] Bugfix: Update DNS status when syncing or not

- .github/pull_request_template.md
- README.md
- controllers/ingress_v1_controller.go
- controllers/ingress_v1beta1_controller.go
- internal/cloudfront/distribution.go
- internal/cloudfront/distribution_test.go
- internal/cloudfront/repository_test.go
- internal/cloudfront/service.go
- internal/cloudfront/service_helpers.go
- internal/k8s/ingress.go
- internal/k8s/ingress_fetcher_v1.go
- internal/k8s/ingress_fetcher_v1_test.go
- internal/k8s/ingress_fetcher_v1beta1.go
- internal/k8s/ingress_fetcher_v1beta1_test.go
- internal/k8s/ingress_test.go
- internal/strhelper/strings.go
This new feature allows the configuration of custom tags for CloudFront distribution.
Tags configured between multiple entries will be merged.
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
annotations:
cdn-origin-controller.gympass.com/cf.tags: |
foo: bar
abc: bca
...
```
> feat(cloudfront): cloudfront tags configuration

- Makefile
- internal/aws/error.go
- internal/cloudfront/aoc_lister.go
- internal/cloudfront/aoc_repository.go
- internal/cloudfront/aoc_repository_test.go
- internal/cloudfront/repository.go
- internal/test/cloudfront_api_mock.go
TSIA
Necessary so that we can eventually support direct access to private S3 buckets that are not set up with static website hosting as origin.
Automated tests.
> [PE1-1248]  Add repository to manage Access Origin Control (AOC)

- internal/cloudfront/aws_models.go
- internal/cloudfront/origin.go
- internal/cloudfront/origin_test.go
- internal/cloudfront/repository_test.go
- Move OAC struct to separate file
- Add type to Origin (Public or Bucket)
- Rename stuff wrongly created as `aoc` to `oac`
- Conditional configuration of s3 origin config in AWS models
- Add logic to handle s3 origin types
https://gympass.atlassian.net/browse/PE1-1251
Automated tests
> [PE1-1251] Add logic to use S3OriginConfig instead of CustomOriginConfig if origin is a bucket

- internal/cloudfront/distribution.go
- internal/cloudfront/origin.go
- internal/cloudfront/repository.go
- internal/cloudfront/repository_test.go
- internal/strhelper/strings.go
- main.go
Update the Distribution repository to delegate syncing and deleting OACs to the OAC repo.
This is needed in order to support private S3 buckets as origins via OAC (Origin Access Control).
Automated tests.
> [PE1-1292] manage OACs in distribution repository

- controllers/predicate_test.go
- internal/config/config.go
- main.go
Removing the implementation of cdn_class var env, this information will be available through the CDNClass resource.
Hot fix.
Manually
> fix: removes unused cdn_class var env

- charts/cdn-origin-controller/Chart.yaml
- charts/cdn-origin-controller/templates/cdnclass.yaml
- internal/route53/repository.go
Checks if existing DNS records have a valid routing policy.
Prevents cryptic errors such as:
```
1 error occurred:
* InvalidChangeBatch: [RRSet with DNS name foo.bar., type A cannot be created as other RRSets exist with the same name and type., RRSet with DNS name foo.bar., type AAAA cannot be created as other RRSets exist with the same name and type., RRSet with DNS name foo.bar., type TXT cannot be created as other RRSets exist with the same name and type.]
status code: 400, request id: 000000000
```
These happen when a record we're upserting already exists (which is usually ok) but have a different routing policy than the one we're upserting (which is not ok).
Manually validated in environment where this was spotted.
> Improve error from bad existing records

- README.md
- api/v1alpha1/cdnclass_types.go
- charts/cdn-origin-controller/templates/crds/cdn.gympass.com_cdnclasses.yaml
- config/crd/bases/cdn.gympass.com_cdnclasses.yaml
- config/samples/cdn_v1alpha1_cdnclass.yaml
- config/samples/cdn_v1alpha1_eu_cdnclass.yaml
- internal/certificate/certificate.go
- internal/certificate/repository.go
- internal/certificate/service.go
- internal/certificate/service_test.go
- internal/cloudfront/service.go
- internal/cloudfront/service_helpers.go
- internal/config/config.go
- internal/k8s/cdnclass.go
- internal/k8s/ingress_fetcher_v1_test.go
- main.go
$TITLE, allowing users to not need to inform one per class. This also allows the same class to potentially be able to use different certs.
This requires less input from users and make it more scalable to deploy on multi-cluster/multi-account environments (eg, using the [Landing Zone pattern](https://docs.aws.amazon.com/prescriptive-guidance/latest/migration-aws-environment/understanding-landing-zones.html)), partially eliminating the need for per-account configuration.
Tests + manually validated.
> [PE1-1796] feat: discover ACM certificates automatically

- README.md
- controllers/ingress_v1_controller.go
- go.mod
- internal/cloudfront/aws_models.go
- internal/cloudfront/distribution_test.go
- internal/cloudfront/function.go
- internal/cloudfront/function_test.go
- internal/cloudfront/origin.go
- internal/cloudfront/origin_test.go
- internal/cloudfront/repository_test.go
- internal/cloudfront/service.go
- internal/cloudfront/service_helpers.go
- internal/k8s/function_association.go
- internal/k8s/function_association_test.go
- internal/k8s/ingress.go
- internal/k8s/ingress_fetcher_v1.go
- internal/k8s/ingress_fetcher_v1_test.go
- internal/k8s/ingress_test.go
- internal/k8s/user_origin.go
- internal/k8s/user_origin_test.go
- $TITLE
- deprecate viewer function arn annotation in favor of more flexible function associations annotation
TODO in upcoming PRs:
- #106 
- #107 
This allows users to specify both [Cloudfront Functions](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-functions.html) and [Lambda@Edge Functions](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-at-the-edge.html) that should be associated with behaviors present in the distribution.
Created, updated and deleted functions from a Distribution based on multiple Ingresses.
> [PE1-1809] Support Function Associations for ingress-based behaviors

- internal/cloudfront/service.go
- internal/cloudfront/service_helpers.go
- internal/k8s/function_association.go
- internal/k8s/ingress.go
- internal/k8s/ingress_fetcher_v1_test.go
- internal/k8s/ingress_test.go
- internal/k8s/user_origin.go
- internal/k8s/user_origin_test.go
Depends on #105.
- $TITLE
- `CDNIngress` now maintains a map of `[]Path` indexed by origin host
- previously it was indexed by Ingress namespaced name, but that's no longer a unique key when dealing with user origins
Refer to #105
Created, updated and deleted functions from a Distribution based on multiple user-origins.
> [PE1-1809] feat(k8s): support function-associations for user-origins

- Makefile
- internal/k8s/ingress.go
- internal/k8s/validation.go
> fix: panic on Ingresses with no HTTP field on rules

- internal/certificate/repository.go
- internal/certificate/service.go
- internal/certificate/service_test.go
- internal/cloudfront/service.go
Ensures that all AWS certificates are being fetched and validated.
> fix: ensuring fetch and validate all certificates from the AWS service
