CONTRIBUTING.md
This is an initial contributing doc that should be improved every we define/chance a process of project contribution.
=> Add initial contributing

.gitignore, README.md, config/rbac/role.yaml, controllers/cdn_origin_controller.go, controllers/cloudfront.go, controllers/cloudfront_test.go, controllers/sort.go, go.mod, hack/add-headers.sh, hack/boilerplate.go.txt, internal/cloudfront/origin.go, internal/cloudfront/origin_test.go, main.go
Changelog:
- Document annotation and how information is gathered from Ingress
- Implement Origin aggregate object
- Implement Origin aggregate builder
- Implement creation of Origin from Ingress
=> [RN-185] Implement CF origin and behavior create op

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/coverage-report.yaml, .github/workflows/pr-checks.yaml, Makefile, README.md, main.go
Changelog:
- Add bug and RFE issue templates
- Add PR checks
- Send coverage report on push
- Run `go mod tidy` in `make vet`
- Add CODEOWNERS
- Add Codacy badges
=> [RN-205] Repo enhancements

controllers/cloudfront.go, controllers/cloudfront_test.go
By creating two separate behaviors per path. Kubernetes Ingress
expects the following behavior given a path "/foo" or "/foo/":
- Request: "/foo"       -> Matches
- Request: "/foo/bar" -> Matches
- Request: "/foobar"  -> No match
So instead of simply appending "*" to the path (which would match
the last case from above) we create two separate behaviors with
path patterns:
- /foo
- /foo/*
A special use case is "/", which results in a single behavior with
"/*" as path pattern.
https://kubernetes.io/docs/concepts/services-networking/ingress/#examples
=> [RN 185/203] Correctly handle Prefix PathType

controllers/cdn_origin_controller.go, controllers/predicate.go, controllers/predicate_internal_test.go
=> [RN 185/204] Add tests for predicate

Dockerfile, helm/cdn-origin-controller/Chart.yaml, helm/cdn-origin-controller/templates/_helpers.tpl, helm/cdn-origin-controller/templates/deployment.yaml, helm/cdn-origin-controller/templates/role.yaml, helm/cdn-origin-controller/templates/role_binding.yaml, helm/cdn-origin-controller/templates/service.yaml, helm/cdn-origin-controller/templates/serviceaccount.yaml, helm/cdn-origin-controller/values.yaml
=> [RN-210] Add Helm Chart

README.md, docs/iam_policy.json
=> [RN-211] Document IAM policy for controlling CloudFront

README.md, controllers/cloudfront.go, controllers/cloudfront_test.go, controllers/ingress_dto.go, controllers/ingress_reconciler.go, controllers/ingress_v1_controller.go, controllers/ingress_v1beta1_controller.go, main.go
=> [RN-225] Support v1beta1 and v1 ingresses

api/v1alpha1/cdnstatus_types.go, config/crd/bases/cdn.gympass.com_cdnstatuses.yaml, controllers/ingress_reconciler.go, controllers/ingress_v1_controller.go, controllers/ingress_v1beta1_controller.go, main.go
Changelog:
- Add custom printColumns with ID, address and aliases to CDNStatus resource
- Add several log messages to make each step in reconciliation more observable
=> [RN-273] Improve user feedback

README.md, controllers/ingress_reconciler.go
=> [RN-273] Record events to CDNStatus as well

.env.example, README.md, config/samples/ingress_v1.yaml, config/samples/multiple_ing_same_group.yaml, controllers/ingress_reconciler.go, controllers/predicate.go, controllers/predicate_test.go, internal/config/config.go
changelog:
- add env var to control CDN class
- add annotation to control CDN class
- add predicate condition based on CDN class
=> [RN-327] Support CDN classes

internal/cloudfront/repository.go, internal/cloudfront/repository_test.go
Co-authored-by: Lucas Caparelli <lucas.caparelli@gympass.com>
=> [RN-331] - fix update distribution when logging is disabled.

api/v1alpha1/cdnstatus_types.go, config/crd/bases/cdn.gympass.com_cdnstatuses.yaml
Co-authored-by: Cesar Okuti <cesar.okuti@gympass.com>
=> [RN-330] Omit .status.dns if null

internal/route53/alias.go, internal/route53/repository.go
With actual TXT records for the same domain as the alias being created.
=> [RN-332] Add prefix to TXT records to avoid collisions

README.md
=> [RN-319] Map user origin fields and annotations

charts/cdn-origin-controller/Chart.yaml, charts/cdn-origin-controller/templates/deployment.yaml, charts/cdn-origin-controller/templates/role.yaml, charts/cdn-origin-controller/values.yaml
- Create a extraArgs config to enable leader-election flag;
- Create role do administrate leader-election.
=> [RN-431] - Add extra args and update rbac

.github/workflows/chart-releaser.yaml, charts/cdn-origin-controller/Chart.yaml, go.mod, go.sum, internal/k8s/ingress.go, internal/k8s/ingress_fetcher_v1_test.go, internal/k8s/user_origin.go, internal/k8s/user_origin_test.go
Add origin field to CDN status resources
https://gympass.atlassian.net/browse/PE1-1247
Automated tests
=> [PE1-1247] add origin access field

internal/cloudfront/distribution.go, internal/cloudfront/oac.go, internal/cloudfront/oac_repository.go, internal/cloudfront/oac_repository_test.go, internal/cloudfront/origin.go, internal/cloudfront/repository.go, internal/cloudfront/repository_test.go, internal/k8s/ingress.go, internal/test/cloudfront_api_mock.go, main.go
Fixes a few issues spotted on validation. Each commit goes into a bit more detail if it's not straightforward.
Required in order to support private S3 buckets as origins directly.
Automated tests + manual testing with complete stack (AWS and what not).
=> [PE1-1252] Fix bugs from e2e validation

charts/cdn-origin-controller/Chart.yaml
TSIA
https://gympass.atlassian.net/browse/PE1-1326
Not tested
=> [PE1-1326] Bump Helm chart to v0.1.0

charts/cdn-origin-controller/Chart.yaml, charts/cdn-origin-controller/values.yaml
TSIA
https://gympass.atlassian.net/browse/PE1-1326
Not tested
=> build: bump Helm chart image version to v0.1.1

.github/workflows/deploy-image.yaml, .github/workflows/pr-checks.yaml
Configuring the GitHub Action workflow to generate an image when push's to the branch dev.
=> chore(gh-action): generate image when push's on dev branch

README.md, api/v1alpha1/cdnclass_types.go, charts/cdn-origin-controller/templates/crds/cdn.gympass.com_cdnclasses.yaml, config/crd/bases/cdn.gympass.com_cdnclasses.yaml, config/samples/cdn_v1alpha1_cdnclass.yaml, internal/cloudfront/service.go, internal/config/config.go, internal/k8s/cdn_class_fetcher.go, internal/k8s/cdnclass.go, internal/route53/alias.go, internal/route53/alias_test.go, internal/route53/repository.go, internal/route53/repository_test.go, main.go
Supporting alias parameter configuration via CDN Classes.
https://gympass.atlassian.net/browse/PE1-1505
Manually and unit tests
=> refac(config): ensure alias configurations through cdn classes

charts/cdn-origin-controller/Chart.yaml, charts/cdn-origin-controller/templates/cdnclass.yaml
Hot fix, adding missing fields to the CDNClass.
helm template.
=> fix: adding txtOwnerValue and createAlias fields to cdn class template

controllers/ingress_v1_controller.go, internal/cloudfront/service.go, internal/k8s/deprecated.go, internal/k8s/validation.go
Depends on #105 and #106 
- $TITLE
- throw a warning event if using deprecated annotations, even if valid
Refer to #105
Validated all error paths and checked events on Ingress.
=> [PE1-1809] feat(k8s): throw error for invalid function associations

README.md, charts/cdn-origin-controller/Chart.yaml, charts/cdn-origin-controller/values.yaml
=> [PE1-1809] Function Associations docs

internal/cloudfront/distribution.go, internal/cloudfront/distribution_test.go
$TITLE, by storing incoming Origins as a map. 
This is so that when we build the desired Distribution while iterating over all Ingresses we don't end up duplicating Origins in it.
This scenario is possible with user-origins, where a single Origin can be referenced by multiple Ingresses (as each user-origin is interpreted as an Ingress).
Without this, user-origins referencing the same origin would end up duplicated and caused duplicated behaviors/paths to be present in the desired state.
Successfully reconciled Ingresses that ran into this.
=> [PE1-1809] fix(DistributionBuilder): make duplicate Origins impossible

go.mod, go.sum, internal/cloudfront/oac.go, internal/cloudfront/oac_test.go
=> fix: generating short name for OAC to avoid bad requests from AWS API

go.mod, internal/cloudfront/oac.go, internal/cloudfront/oac_test.go
=> Fix oac short name
